In [1]:
# Standard data science stack
import pandas as pd
import numpy as np

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

# Modeling
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# Optional: pipeline helpers
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer

# Visualization (optional)
import matplotlib.pyplot as plt
import seaborn as sns

# For reproducibility
RANDOM_STATE = 42

In [3]:
# Replace with your actual path, e.g. "data/burberry_uk_coats.csv"
csv_path = "burberry_uk_coats.csv"

df = pd.read_csv(csv_path)

# Basic shape and head
print("Dataset shape:", df.shape)
df.head()

Dataset shape: (12, 10)

,product_id,brand,product_name,category,gender,color,size_available,price_gbp,material,in_stock
0,BUK001,Burberry,Kensington Heritage Trench Coat,Trench Coat,Women,Honey,4|6|8|10|12|14,1890,Cotton Gabardine,Yes
1,BUK002,Burberry,Westminster Heritage Trench Coat,Trench Coat,Men,Honey,36|38|40|42|44|46,1990,Cotton Gabardine,Yes
2,BUK003,Burberry,Waterloo Long Heritage Trench Coat,Trench Coat,Women,Black,4|6|8|10|12|14,1890,Cotton Gabardine,Yes
3,BUK004,Burberry,Mid-Length Camden Car Coat,Car Coat,Men,Navy,36|38|40|42|44,1390,Cotton Blend,Yes
4,BUK005,Burberry,Reversible Check Wool Coat,Wool Coat,Women,Beige Check,6|8|10|12,1690,Wool,Yes

In [5]:
print(df.columns)

if 'profit' in df.columns and 'sales' in df.columns:
    df['profit_margin'] = df['profit'] / df['sales']
else:
    print("Required columns not found.")

Index(['product_id', 'brand', 'product_name', 'category', 'gender', 'color',
       'size_available', 'price_gbp', 'material', 'in_stock'],
      dtype='object')
Required columns not found.

In [6]:
# Example: fill missing numeric values
numeric_cols = ['age', 'sales', 'profit']  # add others if relevant
for c in numeric_cols:
    if c in df.columns:
        df[c] = df[c].fillna(df[c].median())

# Example: fill missing categorical values
cat_cols = ['gender', 'region']  # adjust to your actual columns
for c in cat_cols:
    if c in df.columns:
        df[c] = df[c].fillna('Unknown')

In [8]:
text_col = 'review_text'

if text_col in df.columns:
    df[text_col] = df[text_col].fillna("").astype(str)
else:
    print("Column not found. Available columns:", df.columns)

Column not found. Available columns: Index(['product_id', 'brand', 'product_name', 'category', 'gender', 'color',
       'size_available', 'price_gbp', 'material', 'in_stock'],
      dtype='object')

In [9]:
# Text features
text_features = [text_col]

# Numeric columns (ensure they exist)
numeric_features = ['age', 'sales']  # add your numeric columns

# Categorical columns to encode later
categorical_features = ['gender', 'region']  # adjust to your data

In [15]:
df.columns = df.columns.str.strip()

In [18]:
print(df.columns.tolist())

['product_id', 'brand', 'product_name', 'category', 'gender', 'color', 'size_available', 'price_gbp', 'material', 'in_stock']

In [19]:
clf_pipeline = Pipeline([
    ('preprocess', preprocessor),
    ('rf', RandomForestClassifier(
        n_estimators=200,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        class_weight='balanced'  # if classes imbalanced
    ))
])

In [24]:
df.head()

,product_id,brand,product_name,category,gender,color,size_available,price_gbp,material,in_stock
0,BUK001,Burberry,Kensington Heritage Trench Coat,Trench Coat,Women,Honey,4|6|8|10|12|14,1890,Cotton Gabardine,Yes
1,BUK002,Burberry,Westminster Heritage Trench Coat,Trench Coat,Men,Honey,36|38|40|42|44|46,1990,Cotton Gabardine,Yes
2,BUK003,Burberry,Waterloo Long Heritage Trench Coat,Trench Coat,Women,Black,4|6|8|10|12|14,1890,Cotton Gabardine,Yes
3,BUK004,Burberry,Mid-Length Camden Car Coat,Car Coat,Men,Navy,36|38|40|42|44,1390,Cotton Blend,Yes
4,BUK005,Burberry,Reversible Check Wool Coat,Wool Coat,Women,Beige Check,6|8|10|12,1690,Wool,Yes

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      12 non-null     object
 1   brand           12 non-null     object
 2   product_name    12 non-null     object
 3   category        12 non-null     object
 4   gender          12 non-null     object
 5   color           12 non-null     object
 6   size_available  12 non-null     object
 7   price_gbp       12 non-null     int64
 8   material        12 non-null     object
 9   in_stock        12 non-null     object
dtypes: int64(1), object(9)
memory usage: 1.1+ KB

In [26]:
print(df.columns)

Index(['product_id', 'brand', 'product_name', 'category', 'gender', 'color',
       'size_available', 'price_gbp', 'material', 'in_stock'],
      dtype='object')

In [35]:
print(df.columns)

Index(['product_id', 'brand', 'product_name', 'category', 'gender', 'color',
       'size_available', 'price_gbp', 'material', 'in_stock'],
      dtype='object')

In [36]:
df.head()

,product_id,brand,product_name,category,gender,color,size_available,price_gbp,material,in_stock
0,BUK001,Burberry,Kensington Heritage Trench Coat,Trench Coat,Women,Honey,4|6|8|10|12|14,1890,Cotton Gabardine,Yes
1,BUK002,Burberry,Westminster Heritage Trench Coat,Trench Coat,Men,Honey,36|38|40|42|44|46,1990,Cotton Gabardine,Yes
2,BUK003,Burberry,Waterloo Long Heritage Trench Coat,Trench Coat,Women,Black,4|6|8|10|12|14,1890,Cotton Gabardine,Yes
3,BUK004,Burberry,Mid-Length Camden Car Coat,Car Coat,Men,Navy,36|38|40|42|44,1390,Cotton Blend,Yes
4,BUK005,Burberry,Reversible Check Wool Coat,Wool Coat,Women,Beige Check,6|8|10|12,1690,Wool,Yes

In [40]:
def get_feature_names(preprocessor):
    feature_names = []

    for name, transformer, cols in preprocessor.transformers_:

        if name == "text":
            if hasattr(transformer, "get_feature_names_out"):
                feature_names.extend(transformer.get_feature_names_out())

        elif name == "num":
            feature_names.extend(cols)

        elif name == "cat":
            feature_names.extend(transformer.get_feature_names_out(cols))

    return feature_names